--
-- Script was generated by Devart dbForge Studio 2022 for SQL Server, Version 6.4.7.0
-- Product home page: http://www.devart.com/dbforge/sql/studio
-- Script date 06.01.2026 23:47:57
-- Server version: 12.0.2000.8
--



USE KHPRO
GO

IF DB_NAME() <> N'KHPRO' SET NOEXEC ON
GO

--
-- Create table [dbo].[USERS]
--
PRINT (N'Create table [dbo].[USERS]')
GO
IF OBJECT_ID(N'dbo.USERS', 'U') IS NULL
CREATE TABLE dbo.USERS (
  ID int IDENTITY,
  KULLANICI nvarchar(15) NOT NULL,
  YONETICI bit NULL,
  SIFRE nvarchar(32) NULL,
  ACIKLAMA varchar(500) NULL,
  y_STOKEKLE bit NULL,
  y_STOKGUNCELLE bit NULL,
  y_STOKSIL bit NULL,
  y_STOKHARSIL bit NULL,
  y_CARIEKLE bit NULL,
  y_CARIGUNCELLE bit NULL,
  y_CARISIL bit NULL,
  y_CARIHARSIL bit NULL,
  y_KASAISLEMEKLE bit NULL,
  y_KASAISLEMSIL bit NULL,
  y_FATEKLE bit NULL,
  y_FATGUNCELLE bit NULL,
  y_FATSIL bit NULL,
  y_BORCEKLE bit NULL,
  y_TAHSILATGIR bit NULL,
  y_HSSATIRDUZENLE bit NULL,
  y_RAPORLAR bit NULL,
  p_FISYAZDIRMA int NULL,
  AKTIF bit NULL CONSTRAINT DF_dbo_USERS_AKTIF DEFAULT (1),
  DELETED bit NULL,
  CREATEDAT datetime2(0) NULL CONSTRAINT DF_dbo_USERS_CREATEDAT DEFAULT (sysdatetime()),
  UPDATEDAT datetime2(0) NULL,
  DELETEDAT datetime2(0) NULL,
  USERID int NULL,
  USERIDUP int NULL,
  CONSTRAINT PK_USERS PRIMARY KEY CLUSTERED (ID),
  CONSTRAINT IX_USERS UNIQUE (KULLANICI)
)
ON [PRIMARY]
GO

--
-- Create table [dbo].[TMPSATIS]
--
PRINT (N'Create table [dbo].[TMPSATIS]')
GO
IF OBJECT_ID(N'dbo.TMPSATIS', 'U') IS NULL
CREATE TABLE dbo.TMPSATIS (
  ID int IDENTITY,
  STOKID int NULL,
  KDV decimal(20, 2) NULL,
  STOKKODU varchar(50) NULL,
  BEKLEMEDE int NULL,
  STOKADI varchar(50) NULL,
  BIRIMADI varchar(50) NULL,
  ADET float NULL,
  FIYAT decimal(20, 2) NULL,
  ISKONTO decimal(20, 2) NULL,
  TOPLAM decimal(20, 2) NULL,
  ALISFIYATI decimal(20, 2) NULL,
  CONSTRAINT PK_tmp_Satis_ID PRIMARY KEY CLUSTERED (ID)
)
ON [PRIMARY]
GO

--
-- Create table [dbo].[T_STOKGRUP]
--
PRINT (N'Create table [dbo].[T_STOKGRUP]')
GO
IF OBJECT_ID(N'dbo.T_STOKGRUP', 'U') IS NULL
CREATE TABLE dbo.T_STOKGRUP (
  ID int IDENTITY,
  GRUPADI varchar(50) NULL,
  AKTIF bit NULL CONSTRAINT DF_dbo_T_STOKGRUP_AKTIF DEFAULT (1),
  DELETED bit NULL,
  CREATEDAT datetime2(0) NULL CONSTRAINT DF_dbo_T_STOKGRUP_CREATEDAT DEFAULT (sysdatetime()),
  UPDATEDAT datetime2(0) NULL,
  DELETEDAT datetime2(0) NULL,
  USERID int NULL,
  USERIDUP int NULL,
  CONSTRAINT PK_T_GRUP_ID PRIMARY KEY CLUSTERED (ID)
)
ON [PRIMARY]
GO

--
-- Create table [dbo].[T_SALON]
--
PRINT (N'Create table [dbo].[T_SALON]')
GO
IF OBJECT_ID(N'dbo.T_SALON', 'U') IS NULL
CREATE TABLE dbo.T_SALON (
  ID int IDENTITY,
  ADI varchar(50) NULL,
  CONSTRAINT PK_T_SALON_ID PRIMARY KEY CLUSTERED (ID)
)
ON [PRIMARY]
GO

--
-- Create table [dbo].[T_REYONRAF]
--
PRINT (N'Create table [dbo].[T_REYONRAF]')
GO
IF OBJECT_ID(N'dbo.T_REYONRAF', 'U') IS NULL
CREATE TABLE dbo.T_REYONRAF (
  ID int IDENTITY,
  REYONRAFADI varchar(50) NULL,
  AKTIF bit NULL CONSTRAINT DF_dbo_T_REYONRAF_AKTIF DEFAULT (1),
  DELETED bit NULL,
  CREATEDAT datetime2(0) NULL CONSTRAINT DF_dbo_T_REYONRAF_CREATEDAT DEFAULT (sysdatetime()),
  UPDATEDAT datetime2(0) NULL,
  DELETEDAT datetime2(0) NULL,
  USERID int NULL,
  USERIDUP int NULL,
  CONSTRAINT PK_T_REYONRAF_ID PRIMARY KEY CLUSTERED (ID)
)
ON [PRIMARY]
GO

--
-- Create table [dbo].[T_MASA]
--
PRINT (N'Create table [dbo].[T_MASA]')
GO
IF OBJECT_ID(N'dbo.T_MASA', 'U') IS NULL
CREATE TABLE dbo.T_MASA (
  ID int IDENTITY,
  SALONID varchar(50) NULL,
  ADI varchar(50) NULL,
  ISLEM_BASLIK_ID int NULL,
  CONSTRAINT PK_T_MASA_ID PRIMARY KEY CLUSTERED (ID)
)
ON [PRIMARY]
GO

--
-- Create table [dbo].[T_MARKA]
--
PRINT (N'Create table [dbo].[T_MARKA]')
GO
IF OBJECT_ID(N'dbo.T_MARKA', 'U') IS NULL
CREATE TABLE dbo.T_MARKA (
  ID int IDENTITY,
  MARKAADI varchar(50) NULL,
  AKTIF bit NULL CONSTRAINT DF_dbo_T_MARKA_AKTIF DEFAULT (1),
  DELETED bit NULL,
  CREATEDAT datetime2(0) NULL CONSTRAINT DF_dbo_T_MARKA_CREATEDAT DEFAULT (sysdatetime()),
  UPDATEDAT datetime2(0) NULL,
  DELETEDAT datetime2(0) NULL,
  USERID int NULL,
  USERIDUP int NULL,
  CONSTRAINT PK_T_MARKA_ID PRIMARY KEY CLUSTERED (ID)
)
ON [PRIMARY]
GO

--
-- Create table [dbo].[T_HSGRUP]
--
PRINT (N'Create table [dbo].[T_HSGRUP]')
GO
IF OBJECT_ID(N'dbo.T_HSGRUP', 'U') IS NULL
CREATE TABLE dbo.T_HSGRUP (
  ID int IDENTITY,
  GRUPADI varchar(50) NOT NULL,
  SIRA int NULL,
  CONSTRAINT PK_T_HSGRUP_ID PRIMARY KEY CLUSTERED (ID)
)
ON [PRIMARY]
GO

--
-- Create table [dbo].[T_HSSIRA]
--
PRINT (N'Create table [dbo].[T_HSSIRA]')
GO
IF OBJECT_ID(N'dbo.T_HSSIRA', 'U') IS NULL
CREATE TABLE dbo.T_HSSIRA (
  ID int IDENTITY,
  GRUPID int NOT NULL,
  STOKKODU varchar(50) NOT NULL,
  SIRA int NULL,
  CONSTRAINT PK_T_HSSIRA_ID PRIMARY KEY CLUSTERED (ID)
)
ON [PRIMARY]
GO

--
-- Create foreign key [FK_T_HSSIRA_GRUPID] on table [dbo].[T_HSSIRA]
--
PRINT (N'Create foreign key [FK_T_HSSIRA_GRUPID] on table [dbo].[T_HSSIRA]')
GO
IF OBJECT_ID('dbo.FK_T_HSSIRA_GRUPID', 'F') IS NULL
  AND OBJECT_ID('dbo.T_HSSIRA', 'U') IS NOT NULL
  AND OBJECT_ID('dbo.T_HSGRUP', 'U') IS NOT NULL
  AND EXISTS (
  SELECT 1 FROM sys.columns WITH (NOLOCK)
  WHERE name = N'GRUPID' AND object_id = OBJECT_ID(N'dbo.T_HSSIRA'))
  AND EXISTS (
  SELECT 1 FROM sys.columns WITH (NOLOCK)
  WHERE name = N'ID' AND object_id = OBJECT_ID(N'dbo.T_HSGRUP'))
ALTER TABLE dbo.T_HSSIRA
  ADD CONSTRAINT FK_T_HSSIRA_GRUPID FOREIGN KEY (GRUPID) REFERENCES dbo.T_HSGRUP (ID) ON DELETE CASCADE ON UPDATE CASCADE
GO

--
-- Create table [dbo].[T_CARIGRUP]
--
PRINT (N'Create table [dbo].[T_CARIGRUP]')
GO
IF OBJECT_ID(N'dbo.T_CARIGRUP', 'U') IS NULL
CREATE TABLE dbo.T_CARIGRUP (
  ID int IDENTITY,
  GRUPADI varchar(50) NOT NULL,
  AKTIF bit NULL CONSTRAINT DF_dbo_T_CARIGRUP_AKTIF DEFAULT (1),
  DELETED bit NULL,
  CREATEDAT datetime2(0) NULL CONSTRAINT DF_dbo_T_CARIGRUP_CREATEDAT DEFAULT (sysdatetime()),
  UPDATEDAT datetime2(0) NULL,
  DELETEDAT datetime2(0) NULL,
  USERID int NULL,
  USERIDUP int NULL,
  CONSTRAINT PK_T_CARIGRUP_ID PRIMARY KEY CLUSTERED (ID)
)
ON [PRIMARY]
GO

SET QUOTED_IDENTIFIER ON
GO

--
-- Create table [dbo].[CARI]
--
PRINT (N'Create table [dbo].[CARI]')
GO
IF OBJECT_ID(N'dbo.CARI', 'U') IS NULL
CREATE TABLE dbo.CARI (
  ID int IDENTITY,
  CARIKODU nvarchar(80) NOT NULL,
  UNVAN nvarchar(100) NOT NULL,
  TARIH datetime NULL,
  GROUPID int NULL,
  MESLEK nvarchar(20) NULL,
  ILCE nvarchar(20) NULL,
  SEHIR nvarchar(20) NULL,
  POSTAKODU nvarchar(10) NULL,
  ULKE nvarchar(20) NULL,
  VERGIDAIRESI nvarchar(20) NULL,
  VERGINO nvarchar(15) NULL,
  BANKA nvarchar(20) NULL,
  BANKAHESAPNO nvarchar(30) NULL,
  ISTELEFONU1 nvarchar(15) NULL,
  ISTELEFONU2 nvarchar(15) NULL,
  FAX nvarchar(15) NULL,
  CEPTELEFONU nvarchar(15) NULL,
  EVTELEFONU nvarchar(15) NULL,
  EMAIL nvarchar(50) NULL,
  ADRES1 nvarchar(50) NULL,
  ADRES2 nvarchar(50) NULL,
  ADRES3 nvarchar(50) NULL,
  ACIKLAMA1 nvarchar(100) NULL,
  ACIKLAMA2 nvarchar(100) NULL,
  ACIKLAMA3 nvarchar(100) NULL,
  RESIM nvarchar(150) NULL,
  YETKILI nvarchar(100) NULL,
  VERESIYE_LIMITI float NULL,
  VERESIYE_UYAR bit NULL,
  VERESIYE_SURESI int NULL,
  EMAIL2 nvarchar(50) NULL,
  EMAIL3 nvarchar(50) NULL,
  TIPI int NULL,
  AKTIF bit NULL CONSTRAINT DF_dbo_CARI_AKTIF DEFAULT (1),
  DELETED bit NULL,
  CREATEDAT datetime2(0) NULL CONSTRAINT DF_dbo_CARI_CREATEDAT DEFAULT (sysdatetime()),
  UPDATEDAT datetime2(0) NULL,
  DELETEDAT datetime2(0) NULL,
  USERID int NULL,
  USERIDUP int NULL,
  TOPLAM_GIREN decimal(18, 4) NULL CONSTRAINT DF_CARI_TOPLAM_GIREN DEFAULT (0),
  TOPLAM_CIKAN decimal(18, 4) NULL CONSTRAINT DF_CARI_TOPLAM_CIKAN DEFAULT (0),
  BAKIYE AS ([TOPLAM_GIREN]-[TOPLAM_CIKAN]) PERSISTED,
  CONSTRAINT PK_CARI PRIMARY KEY CLUSTERED (ID),
  CONSTRAINT IX_CARI UNIQUE (CARIKODU)
)
ON [PRIMARY]
GO

--
-- Create index [IX_CARI_GROUPID] on table [dbo].[CARI]
--
PRINT (N'Create index [IX_CARI_GROUPID] on table [dbo].[CARI]')
GO
IF NOT EXISTS (
  SELECT 1 FROM sys.indexes WITH (NOLOCK)
  WHERE name = N'IX_CARI_GROUPID' AND object_id = OBJECT_ID(N'dbo.CARI'))
  AND EXISTS (
  SELECT 1 FROM sys.columns WITH (NOLOCK)
  WHERE name = N'GROUPID' AND object_id = OBJECT_ID(N'dbo.CARI'))
CREATE INDEX IX_CARI_GROUPID
  ON dbo.CARI (GROUPID)
  ON [PRIMARY]
GO

--
-- Create foreign key [FK_CARI_GROUPID] on table [dbo].[CARI]
--
PRINT (N'Create foreign key [FK_CARI_GROUPID] on table [dbo].[CARI]')
GO
IF OBJECT_ID('dbo.FK_CARI_GROUPID', 'F') IS NULL
  AND OBJECT_ID('dbo.CARI', 'U') IS NOT NULL
  AND OBJECT_ID('dbo.T_CARIGRUP', 'U') IS NOT NULL
  AND EXISTS (
  SELECT 1 FROM sys.columns WITH (NOLOCK)
  WHERE name = N'GROUPID' AND object_id = OBJECT_ID(N'dbo.CARI'))
  AND EXISTS (
  SELECT 1 FROM sys.columns WITH (NOLOCK)
  WHERE name = N'ID' AND object_id = OBJECT_ID(N'dbo.T_CARIGRUP'))
ALTER TABLE dbo.CARI
  ADD CONSTRAINT FK_CARI_GROUPID FOREIGN KEY (GROUPID) REFERENCES dbo.T_CARIGRUP (ID)
GO

--
-- Create table [dbo].[T_BIRIM]
--
PRINT (N'Create table [dbo].[T_BIRIM]')
GO
IF OBJECT_ID(N'dbo.T_BIRIM', 'U') IS NULL
CREATE TABLE dbo.T_BIRIM (
  ID int IDENTITY,
  BIRIMADI varchar(50) NULL,
  AKTIF bit NULL CONSTRAINT DF_dbo_T_BIRIM_AKTIF DEFAULT (1),
  DELETED bit NULL,
  CREATEDAT datetime2(0) NULL CONSTRAINT DF_dbo_T_BIRIM_CREATEDAT DEFAULT (sysdatetime()),
  UPDATEDAT datetime2(0) NULL,
  DELETEDAT datetime2(0) NULL,
  USERID int NULL,
  USERIDUP int NULL,
  CONSTRAINT PK_T_BIRIM_ID PRIMARY KEY CLUSTERED (ID)
)
ON [PRIMARY]
GO

--
-- Create table [dbo].[STOK]
--
PRINT (N'Create table [dbo].[STOK]')
GO
IF OBJECT_ID(N'dbo.STOK', 'U') IS NULL
CREATE TABLE dbo.STOK (
  ID int IDENTITY,
  STOKKODU nvarchar(15) NOT NULL,
  STOKADI nvarchar(255) NOT NULL,
  BARKOD varchar(50) NULL,
  TARIH datetime NULL,
  ACIKLAMA nvarchar(100) NULL,
  BIRIMID int NULL,
  GRUPID int NULL,
  MARKAID int NULL,
  KDV float NULL,
  RESIM varbinary(max) NULL,
  SATISFIYATI float NULL,
  SATISFIYATI2 float NULL,
  SATISFIYATI3 float NULL,
  PLU_NO int NULL,
  ALISFIYATI float NULL,
  KDV_ISTISNA_KODU nvarchar(10) NULL,
  REYONRAFID int NULL,
  TERAZITIP smallint NULL,
  AKTIF bit NULL CONSTRAINT DF_dbo_STOK_AKTIF DEFAULT (1),
  DELETED bit NULL,
  CREATEDAT datetime2(0) NULL CONSTRAINT DF_dbo_STOK_CREATEDAT DEFAULT (sysdatetime()),
  UPDATEDAT datetime2(0) NULL,
  DELETEDAT datetime2(0) NULL,
  USERID int NULL,
  USERIDUP int NULL,
  TOPLAM_GIREN decimal(18, 4) NULL CONSTRAINT DF_STOK_TOPLAM_GIREN DEFAULT (0),
  TOPLAM_CIKAN decimal(18, 4) NULL CONSTRAINT DF_STOK_TOPLAM_CIKAN DEFAULT (0),
  BAKIYE AS ([TOPLAM_GIREN]-[TOPLAM_CIKAN]) PERSISTED,
  CONSTRAINT PK_STOKKARTI PRIMARY KEY CLUSTERED (ID),
  CONSTRAINT KEY_STOK_STOKKODU UNIQUE (STOKKODU)
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO

--
-- Create index [IDX_STOK_BARKOD] on table [dbo].[STOK]
--
PRINT (N'Create index [IDX_STOK_BARKOD] on table [dbo].[STOK]')
GO
IF NOT EXISTS (
  SELECT 1 FROM sys.indexes WITH (NOLOCK)
  WHERE name = N'IDX_STOK_BARKOD' AND object_id = OBJECT_ID(N'dbo.STOK'))
  AND EXISTS (
  SELECT 1 FROM sys.columns WITH (NOLOCK)
  WHERE name = N'BARKOD' AND object_id = OBJECT_ID(N'dbo.STOK'))
CREATE INDEX IDX_STOK_BARKOD
  ON dbo.STOK (BARKOD)
  ON [PRIMARY]
GO

--
-- Create index [IDX_STOK_STOKADI] on table [dbo].[STOK]
--
PRINT (N'Create index [IDX_STOK_STOKADI] on table [dbo].[STOK]')
GO
IF NOT EXISTS (
  SELECT 1 FROM sys.indexes WITH (NOLOCK)
  WHERE name = N'IDX_STOK_STOKADI' AND object_id = OBJECT_ID(N'dbo.STOK'))
  AND EXISTS (
  SELECT 1 FROM sys.columns WITH (NOLOCK)
  WHERE name = N'STOKADI' AND object_id = OBJECT_ID(N'dbo.STOK'))
CREATE INDEX IDX_STOK_STOKADI
  ON dbo.STOK (STOKADI)
  ON [PRIMARY]
GO

--
-- Create index [IX_STOK_BIRIMID] on table [dbo].[STOK]
--
PRINT (N'Create index [IX_STOK_BIRIMID] on table [dbo].[STOK]')
GO
IF NOT EXISTS (
  SELECT 1 FROM sys.indexes WITH (NOLOCK)
  WHERE name = N'IX_STOK_BIRIMID' AND object_id = OBJECT_ID(N'dbo.STOK'))
  AND EXISTS (
  SELECT 1 FROM sys.columns WITH (NOLOCK)
  WHERE name = N'BIRIMID' AND object_id = OBJECT_ID(N'dbo.STOK'))
CREATE INDEX IX_STOK_BIRIMID
  ON dbo.STOK (BIRIMID)
  ON [PRIMARY]
GO

--
-- Create index [IX_STOK_GRUPID] on table [dbo].[STOK]
--
PRINT (N'Create index [IX_STOK_GRUPID] on table [dbo].[STOK]')
GO
IF NOT EXISTS (
  SELECT 1 FROM sys.indexes WITH (NOLOCK)
  WHERE name = N'IX_STOK_GRUPID' AND object_id = OBJECT_ID(N'dbo.STOK'))
  AND EXISTS (
  SELECT 1 FROM sys.columns WITH (NOLOCK)
  WHERE name = N'GRUPID' AND object_id = OBJECT_ID(N'dbo.STOK'))
CREATE INDEX IX_STOK_GRUPID
  ON dbo.STOK (GRUPID)
  ON [PRIMARY]
GO

--
-- Create index [IX_STOK_MARKAID] on table [dbo].[STOK]
--
PRINT (N'Create index [IX_STOK_MARKAID] on table [dbo].[STOK]')
GO
IF NOT EXISTS (
  SELECT 1 FROM sys.indexes WITH (NOLOCK)
  WHERE name = N'IX_STOK_MARKAID' AND object_id = OBJECT_ID(N'dbo.STOK'))
  AND EXISTS (
  SELECT 1 FROM sys.columns WITH (NOLOCK)
  WHERE name = N'MARKAID' AND object_id = OBJECT_ID(N'dbo.STOK'))
CREATE INDEX IX_STOK_MARKAID
  ON dbo.STOK (MARKAID)
  ON [PRIMARY]
GO

--
-- Create index [IX_STOK_REYONRAFID] on table [dbo].[STOK]
--
PRINT (N'Create index [IX_STOK_REYONRAFID] on table [dbo].[STOK]')
GO
IF NOT EXISTS (
  SELECT 1 FROM sys.indexes WITH (NOLOCK)
  WHERE name = N'IX_STOK_REYONRAFID' AND object_id = OBJECT_ID(N'dbo.STOK'))
  AND EXISTS (
  SELECT 1 FROM sys.columns WITH (NOLOCK)
  WHERE name = N'REYONRAFID' AND object_id = OBJECT_ID(N'dbo.STOK'))
CREATE INDEX IX_STOK_REYONRAFID
  ON dbo.STOK (REYONRAFID)
  ON [PRIMARY]
GO

--
-- Create foreign key [FK_STOK_BIRIMID] on table [dbo].[STOK]
--
PRINT (N'Create foreign key [FK_STOK_BIRIMID] on table [dbo].[STOK]')
GO
IF OBJECT_ID('dbo.FK_STOK_BIRIMID', 'F') IS NULL
  AND OBJECT_ID('dbo.STOK', 'U') IS NOT NULL
  AND OBJECT_ID('dbo.T_BIRIM', 'U') IS NOT NULL
  AND EXISTS (
  SELECT 1 FROM sys.columns WITH (NOLOCK)
  WHERE name = N'BIRIMID' AND object_id = OBJECT_ID(N'dbo.STOK'))
  AND EXISTS (
  SELECT 1 FROM sys.columns WITH (NOLOCK)
  WHERE name = N'ID' AND object_id = OBJECT_ID(N'dbo.T_BIRIM'))
ALTER TABLE dbo.STOK
  ADD CONSTRAINT FK_STOK_BIRIMID FOREIGN KEY (BIRIMID) REFERENCES dbo.T_BIRIM (ID)
GO

--
-- Create foreign key [FK_STOK_GRUPID] on table [dbo].[STOK]
--
PRINT (N'Create foreign key [FK_STOK_GRUPID] on table [dbo].[STOK]')
GO
IF OBJECT_ID('dbo.FK_STOK_GRUPID', 'F') IS NULL
  AND OBJECT_ID('dbo.STOK', 'U') IS NOT NULL
  AND OBJECT_ID('dbo.T_STOKGRUP', 'U') IS NOT NULL
  AND EXISTS (
  SELECT 1 FROM sys.columns WITH (NOLOCK)
  WHERE name = N'GRUPID' AND object_id = OBJECT_ID(N'dbo.STOK'))
  AND EXISTS (
  SELECT 1 FROM sys.columns WITH (NOLOCK)
  WHERE name = N'ID' AND object_id = OBJECT_ID(N'dbo.T_STOKGRUP'))
ALTER TABLE dbo.STOK
  ADD CONSTRAINT FK_STOK_GRUPID FOREIGN KEY (GRUPID) REFERENCES dbo.T_STOKGRUP (ID)
GO

--
-- Create foreign key [FK_STOK_MARKAID] on table [dbo].[STOK]
--
PRINT (N'Create foreign key [FK_STOK_MARKAID] on table [dbo].[STOK]')
GO
IF OBJECT_ID('dbo.FK_STOK_MARKAID', 'F') IS NULL
  AND OBJECT_ID('dbo.STOK', 'U') IS NOT NULL
  AND OBJECT_ID('dbo.T_MARKA', 'U') IS NOT NULL
  AND EXISTS (
  SELECT 1 FROM sys.columns WITH (NOLOCK)
  WHERE name = N'MARKAID' AND object_id = OBJECT_ID(N'dbo.STOK'))
  AND EXISTS (
  SELECT 1 FROM sys.columns WITH (NOLOCK)
  WHERE name = N'ID' AND object_id = OBJECT_ID(N'dbo.T_MARKA'))
ALTER TABLE dbo.STOK
  ADD CONSTRAINT FK_STOK_MARKAID FOREIGN KEY (MARKAID) REFERENCES dbo.T_MARKA (ID)
GO

--
-- Create foreign key [FK_STOK_REYONRAFID] on table [dbo].[STOK]
--
PRINT (N'Create foreign key [FK_STOK_REYONRAFID] on table [dbo].[STOK]')
GO
IF OBJECT_ID('dbo.FK_STOK_REYONRAFID', 'F') IS NULL
  AND OBJECT_ID('dbo.STOK', 'U') IS NOT NULL
  AND OBJECT_ID('dbo.T_REYONRAF', 'U') IS NOT NULL
  AND EXISTS (
  SELECT 1 FROM sys.columns WITH (NOLOCK)
  WHERE name = N'REYONRAFID' AND object_id = OBJECT_ID(N'dbo.STOK'))
  AND EXISTS (
  SELECT 1 FROM sys.columns WITH (NOLOCK)
  WHERE name = N'ID' AND object_id = OBJECT_ID(N'dbo.T_REYONRAF'))
ALTER TABLE dbo.STOK
  ADD CONSTRAINT FK_STOK_REYONRAFID FOREIGN KEY (REYONRAFID) REFERENCES dbo.T_REYONRAF (ID)
GO

--
-- Create table [dbo].[POS]
--
PRINT (N'Create table [dbo].[POS]')
GO
IF OBJECT_ID(N'dbo.POS', 'U') IS NULL
CREATE TABLE dbo.POS (
  ID int IDENTITY,
  POSADI nvarchar(30) NOT NULL,
  HESAPKODU nvarchar(20) NULL,
  TERMINALNO nvarchar(20) NULL,
  BANKAADI nvarchar(30) NULL,
  UYEISYERINO nvarchar(20) NULL,
  AKTIF bit NULL CONSTRAINT DF_dbo_POS_AKTIF DEFAULT (1),
  DELETED bit NULL,
  CREATEDAT datetime2(0) NULL CONSTRAINT DF_dbo_POS_CREATEDAT DEFAULT (sysdatetime()),
  UPDATEDAT datetime2(0) NULL,
  DELETEDAT datetime2(0) NULL,
  USERID int NULL,
  USERIDUP int NULL,
  TOPLAM_GIREN decimal(18, 4) NULL DEFAULT (0),
  TOPLAM_CIKAN decimal(18, 4) NULL DEFAULT (0),
  BAKIYE AS ([TOPLAM_GIREN]-[TOPLAM_CIKAN]) PERSISTED,
  CONSTRAINT PK_POSLAR PRIMARY KEY CLUSTERED (ID)
)
ON [PRIMARY]
GO

--
-- Create index [UK_POS_POSADI] on table [dbo].[POS]
--
PRINT (N'Create index [UK_POS_POSADI] on table [dbo].[POS]')
GO
IF NOT EXISTS (
  SELECT 1 FROM sys.indexes WITH (NOLOCK)
  WHERE name = N'UK_POS_POSADI' AND object_id = OBJECT_ID(N'dbo.POS'))
  AND EXISTS (
  SELECT 1 FROM sys.columns WITH (NOLOCK)
  WHERE name = N'POSADI' AND object_id = OBJECT_ID(N'dbo.POS'))
CREATE UNIQUE INDEX UK_POS_POSADI
  ON dbo.POS (POSADI)
  ON [PRIMARY]
GO

--
-- Create table [dbo].[ISLEM_BASLIK]
--
PRINT (N'Create table [dbo].[ISLEM_BASLIK]')
GO
IF OBJECT_ID(N'dbo.ISLEM_BASLIK', 'U') IS NULL
CREATE TABLE dbo.ISLEM_BASLIK (
  ID int IDENTITY,
  ISLEMTURU tinyint NOT NULL,
  ODEMETURU varchar(50) NOT NULL,
  ISLEMTARIHI datetime NOT NULL,
  CARIID int NOT NULL,
  POSID int NOT NULL,
  EVRAKNO nvarchar(100) NULL,
  GIREN decimal(18, 4) NULL DEFAULT (0),
  CIKAN decimal(18, 4) NULL DEFAULT (0),
  TUTAR decimal(18, 2) NULL,
  KDVORANI decimal(5, 2) NULL,
  KDVTUTARI decimal(18, 2) NULL,
  ISKONTO_ORANI decimal(5, 2) NULL,
  ISKONTO_TUTARI decimal(18, 2) NULL,
  ACIKLAMA1 nvarchar(150) NULL,
  ACIKLAMA2 nvarchar(150) NULL,
  CREATEDAT datetime2(0) NULL DEFAULT (sysdatetime()),
  UPDATEDAT datetime2(0) NULL,
  USERID int NULL,
  USERIDUP int NULL,
  PRIMARY KEY CLUSTERED (ID)
)
ON [PRIMARY]
GO

--
-- Create index [IX_ISLEM_BASLIK_CARI] on table [dbo].[ISLEM_BASLIK]
--
PRINT (N'Create index [IX_ISLEM_BASLIK_CARI] on table [dbo].[ISLEM_BASLIK]')
GO
IF NOT EXISTS (
  SELECT 1 FROM sys.indexes WITH (NOLOCK)
  WHERE name = N'IX_ISLEM_BASLIK_CARI' AND object_id = OBJECT_ID(N'dbo.ISLEM_BASLIK'))
  AND EXISTS (
  SELECT 1 FROM sys.columns WITH (NOLOCK)
  WHERE name = N'CARIID' AND object_id = OBJECT_ID(N'dbo.ISLEM_BASLIK'))
CREATE INDEX IX_ISLEM_BASLIK_CARI
  ON dbo.ISLEM_BASLIK (CARIID)
  ON [PRIMARY]
GO

--
-- Create index [IX_ISLEM_BASLIK_TARIH] on table [dbo].[ISLEM_BASLIK]
--
PRINT (N'Create index [IX_ISLEM_BASLIK_TARIH] on table [dbo].[ISLEM_BASLIK]')
GO
IF NOT EXISTS (
  SELECT 1 FROM sys.indexes WITH (NOLOCK)
  WHERE name = N'IX_ISLEM_BASLIK_TARIH' AND object_id = OBJECT_ID(N'dbo.ISLEM_BASLIK'))
  AND EXISTS (
  SELECT 1 FROM sys.columns WITH (NOLOCK)
  WHERE name = N'ISLEMTARIHI' AND object_id = OBJECT_ID(N'dbo.ISLEM_BASLIK'))
CREATE INDEX IX_ISLEM_BASLIK_TARIH
  ON dbo.ISLEM_BASLIK (ISLEMTARIHI)
  ON [PRIMARY]
GO

SET ANSI_NULLS ON
GO

--
-- Create trigger [TRG_ISLEM_BASLIK_GUNCELLE] on table [dbo].[ISLEM_BASLIK]
--
GO
PRINT (N'Create trigger [TRG_ISLEM_BASLIK_GUNCELLE] on table [dbo].[ISLEM_BASLIK]')
GO
IF OBJECT_ID(N'dbo.TRG_ISLEM_BASLIK_GUNCELLE', 'TR') IS NULL
EXEC sp_executesql N'CREATE TRIGGER dbo.TRG_ISLEM_BASLIK_GUNCELLE
ON dbo.ISLEM_BASLIK
AFTER INSERT, UPDATE, DELETE
AS
BEGIN
    SET NOCOUNT ON;

    /* ================================
       1️⃣ CARI – ESKİ KAYITLARI GERİ AL
       ================================ */
    UPDATE C
    SET
        TOPLAM_GIREN = TOPLAM_GIREN - ISNULL(D.GIREN,0),
        TOPLAM_CIKAN = TOPLAM_CIKAN - ISNULL(D.CIKAN,0)
    FROM dbo.CARI C
    INNER JOIN deleted D ON D.CARIID = C.ID
    WHERE D.ISLEMTURU IN (1,5,6);

    /* ================================
       2️⃣ POS – ESKİ KAYITLARI GERİ AL
       (SADECE ODEMETURU = 2)
       ================================ */
    UPDATE P
    SET
        TOPLAM_GIREN = TOPLAM_GIREN - ISNULL(D.GIREN,0),
        TOPLAM_CIKAN = TOPLAM_CIKAN - ISNULL(D.CIKAN,0)
    FROM dbo.POS P
    INNER JOIN deleted D ON D.POSID = P.ID
    WHERE D.ODEMETURU = 2
      AND D.ISLEMTURU IN (1,5,6);

    /* ================================
       3️⃣ CARI – YENİ KAYITLARI EKLE
       ================================ */
    UPDATE C
    SET
        TOPLAM_GIREN = TOPLAM_GIREN + ISNULL(I.GIREN,0),
        TOPLAM_CIKAN = TOPLAM_CIKAN + ISNULL(I.CIKAN,0)
    FROM dbo.CARI C
    INNER JOIN inserted I ON I.CARIID = C.ID
    WHERE I.ISLEMTURU IN (1,5,6);

    /* ================================
       4️⃣ POS – YENİ KAYITLARI EKLE
       (SADECE ODEMETURU = 2)
       ================================ */
    UPDATE P
    SET
        TOPLAM_GIREN = TOPLAM_GIREN + ISNULL(I.GIREN,0),
        TOPLAM_CIKAN = TOPLAM_CIKAN + ISNULL(I.CIKAN,0)
    FROM dbo.POS P
    INNER JOIN inserted I ON I.POSID = P.ID
    WHERE I.ODEMETURU = 2
      AND I.ISLEMTURU IN (1,5,6);

END'
GO

--
-- Create table [dbo].[ISLEM_H]
--
PRINT (N'Create table [dbo].[ISLEM_H]')
GO
IF OBJECT_ID(N'dbo.ISLEM_H', 'U') IS NULL
CREATE TABLE dbo.ISLEM_H (
  ID int IDENTITY,
  ISLEMID int NOT NULL,
  ISLEMTURU tinyint NOT NULL,
  ODEMETURU tinyint NOT NULL,
  ISLEMTARIHI datetime NOT NULL,
  CARIID int NOT NULL,
  STOKID int NOT NULL,
  POSID int NOT NULL,
  EVRAKNO nvarchar(100) NULL,
  MIKTAR decimal(18, 4) NULL,
  BIRIMFIYAT decimal(18, 4) NULL,
  GIREN decimal(18, 4) NULL DEFAULT (0),
  CIKAN decimal(18, 4) NULL DEFAULT (0),
  TUTAR decimal(18, 2) NULL,
  BIRIMID int NULL,
  BIRIMADI varchar(50) NULL,
  KDVORANI decimal(5, 2) NULL,
  KDVTUTARI decimal(18, 2) NULL,
  ISKONTO_ORANI decimal(5, 2) NULL,
  ISKONTO_TUTARI decimal(18, 2) NULL,
  ALISFIYATI decimal(20, 2) NULL,
  ACIKLAMA1 nvarchar(150) NULL,
  ACIKLAMA2 nvarchar(150) NULL,
  CREATEDAT datetime2(0) NULL DEFAULT (sysdatetime()),
  UPDATEDAT datetime2(0) NULL,
  USERID int NULL,
  USERIDUP int NULL,
  PRIMARY KEY CLUSTERED (ID)
)
ON [PRIMARY]
GO

--
-- Create index [IX_ISLEM_H_ISLEMID] on table [dbo].[ISLEM_H]
--
PRINT (N'Create index [IX_ISLEM_H_ISLEMID] on table [dbo].[ISLEM_H]')
GO
IF NOT EXISTS (
  SELECT 1 FROM sys.indexes WITH (NOLOCK)
  WHERE name = N'IX_ISLEM_H_ISLEMID' AND object_id = OBJECT_ID(N'dbo.ISLEM_H'))
  AND EXISTS (
  SELECT 1 FROM sys.columns WITH (NOLOCK)
  WHERE name = N'ISLEMID' AND object_id = OBJECT_ID(N'dbo.ISLEM_H'))
CREATE INDEX IX_ISLEM_H_ISLEMID
  ON dbo.ISLEM_H (ISLEMID)
  ON [PRIMARY]
GO

--
-- Create index [IX_ISLEM_H_TARIH] on table [dbo].[ISLEM_H]
--
PRINT (N'Create index [IX_ISLEM_H_TARIH] on table [dbo].[ISLEM_H]')
GO
IF NOT EXISTS (
  SELECT 1 FROM sys.indexes WITH (NOLOCK)
  WHERE name = N'IX_ISLEM_H_TARIH' AND object_id = OBJECT_ID(N'dbo.ISLEM_H'))
  AND EXISTS (
  SELECT 1 FROM sys.columns WITH (NOLOCK)
  WHERE name = N'ISLEMTARIHI' AND object_id = OBJECT_ID(N'dbo.ISLEM_H'))
CREATE INDEX IX_ISLEM_H_TARIH
  ON dbo.ISLEM_H (ISLEMTARIHI)
  ON [PRIMARY]
GO

--
-- Create index [IX_ISLEM_H_TIP_HESAP] on table [dbo].[ISLEM_H]
--
PRINT (N'Create index [IX_ISLEM_H_TIP_HESAP] on table [dbo].[ISLEM_H]')
GO
IF NOT EXISTS (
  SELECT 1 FROM sys.indexes WITH (NOLOCK)
  WHERE name = N'IX_ISLEM_H_TIP_HESAP' AND object_id = OBJECT_ID(N'dbo.ISLEM_H'))
  AND EXISTS (
  SELECT 1 FROM sys.columns WITH (NOLOCK)
  WHERE name = N'ISLEMTURU' AND object_id = OBJECT_ID(N'dbo.ISLEM_H'))
  AND EXISTS (
  SELECT 1 FROM sys.columns WITH (NOLOCK)
  WHERE name = N'CARIID' AND object_id = OBJECT_ID(N'dbo.ISLEM_H'))
CREATE INDEX IX_ISLEM_H_TIP_HESAP
  ON dbo.ISLEM_H (ISLEMTURU, CARIID)
  ON [PRIMARY]
GO

--
-- Create trigger [TRG_ISLEM_H_UPDATE_TOTALS] on table [dbo].[ISLEM_H]
--
GO
PRINT (N'Create trigger [TRG_ISLEM_H_UPDATE_TOTALS] on table [dbo].[ISLEM_H]')
GO
IF OBJECT_ID(N'dbo.TRG_ISLEM_H_UPDATE_TOTALS', 'TR') IS NULL
EXEC sp_executesql N'CREATE TRIGGER dbo.TRG_ISLEM_H_UPDATE_TOTALS
ON dbo.ISLEM_H
AFTER INSERT, UPDATE, DELETE
AS
BEGIN
    SET NOCOUNT ON;

    /* =====================================================
       STOK (ADET / MİKTAR)
    ===================================================== */
    ;WITH X AS (
        SELECT STOKID,
               SUM(GIREN) AS GIREN,
               SUM(CIKAN) AS CIKAN
        FROM (
            SELECT STOKID, GIREN, CIKAN
            FROM inserted
            WHERE ISLEMTURU IN (1,2,3)

            UNION ALL

            SELECT STOKID, -GIREN, -CIKAN
            FROM deleted
            WHERE ISLEMTURU IN (1,2,3)
        ) T
        GROUP BY STOKID
    )
    UPDATE S
    SET
        S.TOPLAM_GIREN += X.GIREN,
        S.TOPLAM_CIKAN += X.CIKAN
    FROM dbo.STOK S
    JOIN X ON X.STOKID = S.ID;
  

END'
GO

--
-- Create foreign key [FK_ISLEM_H_ISLEMID] on table [dbo].[ISLEM_H]
--
PRINT (N'Create foreign key [FK_ISLEM_H_ISLEMID] on table [dbo].[ISLEM_H]')
GO
IF OBJECT_ID('dbo.FK_ISLEM_H_ISLEMID', 'F') IS NULL
  AND OBJECT_ID('dbo.ISLEM_H', 'U') IS NOT NULL
  AND OBJECT_ID('dbo.ISLEM_BASLIK', 'U') IS NOT NULL
  AND EXISTS (
  SELECT 1 FROM sys.columns WITH (NOLOCK)
  WHERE name = N'ISLEMID' AND object_id = OBJECT_ID(N'dbo.ISLEM_H'))
  AND EXISTS (
  SELECT 1 FROM sys.columns WITH (NOLOCK)
  WHERE name = N'ID' AND object_id = OBJECT_ID(N'dbo.ISLEM_BASLIK'))
ALTER TABLE dbo.ISLEM_H
  ADD CONSTRAINT FK_ISLEM_H_ISLEMID FOREIGN KEY (ISLEMID) REFERENCES dbo.ISLEM_BASLIK (ID)
GO

--
-- Create procedure [dbo].[SP_REBUILD_ALL_TOTALS]
--
GO
PRINT (N'Create procedure [dbo].[SP_REBUILD_ALL_TOTALS]')
GO
IF OBJECT_ID(N'dbo.SP_REBUILD_ALL_TOTALS', 'P') IS NULL
EXEC sp_executesql N'CREATE PROCEDURE dbo.SP_REBUILD_ALL_TOTALS
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;

    BEGIN TRAN;

    /* =====================================================
       1️⃣ CARI TOPLAMLARINI SIFIRLA
    ===================================================== */
    UPDATE dbo.CARI
    SET
        TOPLAM_GIREN = 0,
        TOPLAM_CIKAN = 0;

    /* =====================================================
       2️⃣ POS TOPLAMLARINI SIFIRLA
    ===================================================== */
    UPDATE dbo.POS
    SET
        TOPLAM_GIREN = 0,
        TOPLAM_CIKAN = 0;

    /* =====================================================
       3️⃣ STOK TOPLAMLARINI SIFIRLA
    ===================================================== */
    UPDATE dbo.STOK
    SET
        TOPLAM_GIREN = 0,
        TOPLAM_CIKAN = 0;

    /* =====================================================
       4️⃣ CARI – ISLEM_BASLIK’TAN HESAPLA
       ISLEMTURU:
       1,5 = GİRİŞ
       6   = ÇIKIŞ
    ===================================================== */
    ;WITH CARI_T AS (
        SELECT
            CARIID,
            SUM(GIREN) AS GIREN,
            SUM(CIKAN) AS CIKAN
        FROM dbo.ISLEM_BASLIK
        WHERE ISLEMTURU IN (1,5,6)
        GROUP BY CARIID
    )
    UPDATE C
    SET
        C.TOPLAM_GIREN = T.GIREN,
        C.TOPLAM_CIKAN = T.CIKAN
    FROM dbo.CARI C
    JOIN CARI_T T ON T.CARIID = C.ID;

    /* =====================================================
       5️⃣ POS – SADECE ODEMETURU = 2
    ===================================================== */
    ;WITH POS_T AS (
        SELECT
            POSID,
            SUM(GIREN) AS GIREN,
            SUM(CIKAN) AS CIKAN
        FROM dbo.ISLEM_BASLIK
        WHERE ODEMETURU = 2
          AND ISLEMTURU IN (1,5,6)
        GROUP BY POSID
    )
    UPDATE P
    SET
        P.TOPLAM_GIREN = T.GIREN,
        P.TOPLAM_CIKAN = T.CIKAN
    FROM dbo.POS P
    JOIN POS_T T ON T.POSID = P.ID;

    /* =====================================================
       6️⃣ STOK – ISLEM_H’TAN HESAPLA
       ISLEMTURU:
       1,2 = GİRİŞ
       3   = ÇIKIŞ
    ===================================================== */
    ;WITH STOK_T AS (
        SELECT
            STOKID,
            SUM(GIREN) AS GIREN,
            SUM(CIKAN) AS CIKAN
        FROM dbo.ISLEM_H
        WHERE ISLEMTURU IN (1,2,3)
        GROUP BY STOKID
    )
    UPDATE S
    SET
        S.TOPLAM_GIREN = T.GIREN,
        S.TOPLAM_CIKAN = T.CIKAN
    FROM dbo.STOK S
    JOIN STOK_T T ON T.STOKID = S.ID;

    COMMIT TRAN;
END'
GO

--
-- Create table [dbo].[AYARLAR]
--
PRINT (N'Create table [dbo].[AYARLAR]')
GO
IF OBJECT_ID(N'dbo.AYARLAR', 'U') IS NULL
CREATE TABLE dbo.AYARLAR (
  ID int IDENTITY,
  FIRMAADI varchar(50) NULL,
  FIRMATELEFON varchar(50) NULL,
  FIRMAADRES varchar(50) NULL,
  FIRMAIL varchar(50) NULL,
  FIRMAILCE varchar(50) NULL,
  FIRMAEPOSTA varchar(50) NULL,
  LISANSKEY varchar(500) NULL,
  OTO_YEDEK bit NULL,
  OTO_YEDEK_DIZINI varchar(500) NULL,
  CONSTRAINT PK_AYARLAR_ID PRIMARY KEY CLUSTERED (ID)
)
ON [PRIMARY]
GO
SET NOEXEC OFF
GO