USE KHPRO
GO

IF DB_NAME() <> N'KHPRO' SET NOEXEC ON
GO

--
-- Create table [dbo].[USERS]
--
PRINT (N'Create table [dbo].[USERS]')
GO
CREATE TABLE dbo.USERS (
  ID int IDENTITY,
  KULLANICI nvarchar(15) NOT NULL,
  YONETICI bit NULL DEFAULT (0),
  SIFRE nvarchar(32) NULL,
  ACIKLAMA varchar(500) NULL,
  y_STOKEKLE bit NULL,
  y_STOKGUNCELLE bit NULL,
  y_STOKSIL bit NULL,
  y_STOKHARSIL bit NULL,
  y_CARIEKLE bit NULL,
  y_CARIGUNCELLE bit NULL,
  y_CARISIL bit NULL,
  y_CARIHARSIL bit NULL,
  y_KASAISLEMEKLE bit NULL,
  y_KASAISLEMSIL bit NULL,
  y_FATEKLE bit NULL,
  y_FATGUNCELLE bit NULL,
  y_FATSIL bit NULL,
  y_BORCEKLE bit NULL,
  y_TAHSILATGIR bit NULL,
  y_HSSATIRDUZENLE bit NULL,
  p_FISYAZDIRMA int NULL,
  AKTIF bit NULL CONSTRAINT DF_dbo_USERS_AKTIF DEFAULT (1),
  DELETED bit NULL CONSTRAINT DF_dbo_USERS_DELETED DEFAULT (0),
  CREATEDAT datetime2(0) NULL CONSTRAINT DF_dbo_USERS_CREATEDAT DEFAULT (sysdatetime()),
  UPDATEDAT datetime2(0) NULL,
  DELETEDAT datetime2(0) NULL,
  USERID int NULL,
  USERIDUP int NULL,
  CONSTRAINT IX_USERS UNIQUE (KULLANICI)
)
ON [PRIMARY]
GO

--
-- Create table [dbo].[TMPSATIS]
--
PRINT (N'Create table [dbo].[TMPSATIS]')
GO
CREATE TABLE dbo.TMPSATIS (
  ID int IDENTITY,
  STOKID int NULL,
  KDV decimal(20, 2) NULL,
  STOKKODU varchar(50) NULL,
  BEKLEMEDE int NULL,
  STOKADI varchar(50) NULL,
  BIRIMADI varchar(50) NULL,
  ADET float NULL,
  FIYAT decimal(20, 2) NULL,
  ISKONTO decimal(20, 2) NULL,
  TOPLAM decimal(20, 2) NULL,
  CONSTRAINT PK_tmp_Satis_ID PRIMARY KEY CLUSTERED (ID)
)
ON [PRIMARY]
GO

--
-- Create table [dbo].[T_STOKGRUP]
--
PRINT (N'Create table [dbo].[T_STOKGRUP]')
GO
CREATE TABLE dbo.T_STOKGRUP (
  ID int IDENTITY,
  GRUPADI varchar(50) NULL,
  AKTIF bit NULL CONSTRAINT DF_dbo_T_STOKGRUP_AKTIF DEFAULT (1),
  DELETED bit NULL CONSTRAINT DF_dbo_T_STOKGRUP_DELETED DEFAULT (0),
  CREATEDAT datetime2(0) NULL CONSTRAINT DF_dbo_T_STOKGRUP_CREATEDAT DEFAULT (sysdatetime()),
  UPDATEDAT datetime2(0) NULL,
  DELETEDAT datetime2(0) NULL,
  USERID int NULL,
  USERIDUP int NULL,
  CONSTRAINT PK_T_GRUP_ID PRIMARY KEY CLUSTERED (ID)
)
ON [PRIMARY]
GO

--
-- Create table [dbo].[T_REYONRAF]
--
PRINT (N'Create table [dbo].[T_REYONRAF]')
GO
CREATE TABLE dbo.T_REYONRAF (
  ID int IDENTITY,
  REYONRAFADI varchar(50) NULL,
  AKTIF bit NULL CONSTRAINT DF_dbo_T_REYONRAF_AKTIF DEFAULT (1),
  DELETED bit NULL CONSTRAINT DF_dbo_T_REYONRAF_DELETED DEFAULT (0),
  CREATEDAT datetime2(0) NULL CONSTRAINT DF_dbo_T_REYONRAF_CREATEDAT DEFAULT (sysdatetime()),
  UPDATEDAT datetime2(0) NULL,
  DELETEDAT datetime2(0) NULL,
  USERID int NULL,
  USERIDUP int NULL,
  CONSTRAINT PK_T_REYONRAF_ID PRIMARY KEY CLUSTERED (ID)
)
ON [PRIMARY]
GO

--
-- Create table [dbo].[T_MARKA]
--
PRINT (N'Create table [dbo].[T_MARKA]')
GO
CREATE TABLE dbo.T_MARKA (
  ID int IDENTITY,
  MARKAADI varchar(50) NULL,
  AKTIF bit NULL CONSTRAINT DF_dbo_T_MARKA_AKTIF DEFAULT (1),
  DELETED bit NULL CONSTRAINT DF_dbo_T_MARKA_DELETED DEFAULT (0),
  CREATEDAT datetime2(0) NULL CONSTRAINT DF_dbo_T_MARKA_CREATEDAT DEFAULT (sysdatetime()),
  UPDATEDAT datetime2(0) NULL,
  DELETEDAT datetime2(0) NULL,
  USERID int NULL,
  USERIDUP int NULL,
  CONSTRAINT PK_T_MARKA_ID PRIMARY KEY CLUSTERED (ID)
)
ON [PRIMARY]
GO

--
-- Create table [dbo].[T_HSSIRA]
--
PRINT (N'Create table [dbo].[T_HSSIRA]')
GO
CREATE TABLE dbo.T_HSSIRA (
  ID int IDENTITY,
  GRUPID int NOT NULL,
  STOKKODU varchar(50) NOT NULL,
  SIRA int NULL,
  CONSTRAINT PK_T_HSSIRA_ID PRIMARY KEY CLUSTERED (ID)
)
ON [PRIMARY]
GO

--
-- Create table [dbo].[T_HSGRUP]
--
PRINT (N'Create table [dbo].[T_HSGRUP]')
GO
CREATE TABLE dbo.T_HSGRUP (
  ID int IDENTITY,
  GRUPADI varchar(50) NOT NULL,
  SIRA int NULL,
  CONSTRAINT PK_T_HSGRUP_ID PRIMARY KEY CLUSTERED (ID)
)
ON [PRIMARY]
GO

--
-- Create table [dbo].[T_CARIGRUP]
--
PRINT (N'Create table [dbo].[T_CARIGRUP]')
GO
CREATE TABLE dbo.T_CARIGRUP (
  ID int IDENTITY,
  GRUPADI varchar(50) NOT NULL,
  AKTIF bit NULL CONSTRAINT DF_dbo_T_CARIGRUP_AKTIF DEFAULT (1),
  DELETED bit NULL CONSTRAINT DF_dbo_T_CARIGRUP_DELETED DEFAULT (0),
  CREATEDAT datetime2(0) NULL CONSTRAINT DF_dbo_T_CARIGRUP_CREATEDAT DEFAULT (sysdatetime()),
  UPDATEDAT datetime2(0) NULL,
  DELETEDAT datetime2(0) NULL,
  USERID int NULL,
  USERIDUP int NULL,
  CONSTRAINT PK_T_CARIGRUP_ID PRIMARY KEY CLUSTERED (ID)
)
ON [PRIMARY]
GO

--
-- Create table [dbo].[T_BIRIM]
--
PRINT (N'Create table [dbo].[T_BIRIM]')
GO
CREATE TABLE dbo.T_BIRIM (
  ID int IDENTITY,
  BIRIMADI varchar(50) NULL,
  AKTIF bit NULL CONSTRAINT DF_dbo_T_BIRIM_AKTIF DEFAULT (1),
  DELETED bit NULL CONSTRAINT DF_dbo_T_BIRIM_DELETED DEFAULT (0),
  CREATEDAT datetime2(0) NULL CONSTRAINT DF_dbo_T_BIRIM_CREATEDAT DEFAULT (sysdatetime()),
  UPDATEDAT datetime2(0) NULL,
  DELETEDAT datetime2(0) NULL,
  USERID int NULL,
  USERIDUP int NULL,
  CONSTRAINT PK_T_BIRIM_ID PRIMARY KEY CLUSTERED (ID)
)
ON [PRIMARY]
GO

--
-- Create table [dbo].[STOK]
--
PRINT (N'Create table [dbo].[STOK]')
GO
CREATE TABLE dbo.STOK (
  ID int IDENTITY,
  STOKKODU nvarchar(15) NOT NULL,
  STOKADI nvarchar(255) NOT NULL,
  BARKOD varchar(50) NULL,
  URUNMARKASI nvarchar(20) NULL,
  TARIH datetime NULL,
  ACIKLAMA nvarchar(100) NULL,
  BIRIMID int NULL,
  GRUPID int NULL,
  MARKAID int NULL,
  KDV float NULL CONSTRAINT DF_STOKKARTI_KDV DEFAULT (0),
  RESIM varbinary(max) NULL,
  SATISFIYATI float NULL CONSTRAINT DF_STOKKARTI_SATISFIYATI DEFAULT (0),
  SATISFIYATI2 float NULL CONSTRAINT DF_STOKKARTI_SATISFIYATI2 DEFAULT (0),
  SATISFIYATI3 float NULL CONSTRAINT DF_STOKKARTI_SATISFIYATI3 DEFAULT (0),
  PLU_NO int NULL CONSTRAINT DF_STOKKARTI_PLU_NO DEFAULT (0),
  ALISFIYATI float NULL CONSTRAINT DF_STOKKARTI_ALISFIYATI DEFAULT (0),
  KDV_ISTISNA_KODU nvarchar(10) NULL,
  REYONRAFID int NULL,
  TERAZITIP smallint NULL DEFAULT (0),
  AKTIF bit NULL CONSTRAINT DF_dbo_STOK_AKTIF DEFAULT (1),
  DELETED bit NULL CONSTRAINT DF_dbo_STOK_DELETED DEFAULT (0),
  CREATEDAT datetime2(0) NULL CONSTRAINT DF_dbo_STOK_CREATEDAT DEFAULT (sysdatetime()),
  UPDATEDAT datetime2(0) NULL,
  DELETEDAT datetime2(0) NULL,
  USERID int NULL,
  USERIDUP int NULL,
  CONSTRAINT PK_STOKKARTI PRIMARY KEY CLUSTERED (ID),
  CONSTRAINT KEY_STOK_STOKADI UNIQUE (STOKADI),
  CONSTRAINT KEY_STOK_STOKKODU UNIQUE (STOKKODU)
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO

--
-- Create foreign key [FK_STOK_BIRIMID] on table [dbo].[STOK]
--
PRINT (N'Create foreign key [FK_STOK_BIRIMID] on table [dbo].[STOK]')
GO
ALTER TABLE dbo.STOK
  ADD CONSTRAINT FK_STOK_BIRIMID FOREIGN KEY (BIRIMID) REFERENCES dbo.T_BIRIM (ID)
GO

--
-- Create foreign key [FK_STOK_GRUPID] on table [dbo].[STOK]
--
PRINT (N'Create foreign key [FK_STOK_GRUPID] on table [dbo].[STOK]')
GO
ALTER TABLE dbo.STOK
  ADD CONSTRAINT FK_STOK_GRUPID FOREIGN KEY (GRUPID) REFERENCES dbo.T_STOKGRUP (ID)
GO

--
-- Create foreign key [FK_STOK_MARKAID] on table [dbo].[STOK]
--
PRINT (N'Create foreign key [FK_STOK_MARKAID] on table [dbo].[STOK]')
GO
ALTER TABLE dbo.STOK
  ADD CONSTRAINT FK_STOK_MARKAID FOREIGN KEY (MARKAID) REFERENCES dbo.T_MARKA (ID)
GO

--
-- Create foreign key [FK_STOK_REYONRAFID] on table [dbo].[STOK]
--
PRINT (N'Create foreign key [FK_STOK_REYONRAFID] on table [dbo].[STOK]')
GO
ALTER TABLE dbo.STOK
  ADD CONSTRAINT FK_STOK_REYONRAFID FOREIGN KEY (REYONRAFID) REFERENCES dbo.T_REYONRAF (ID)
GO

--
-- Create table [dbo].[STOK_H]
--
PRINT (N'Create table [dbo].[STOK_H]')
GO
CREATE TABLE dbo.STOK_H (
  ID int IDENTITY,
  STOKID int NOT NULL CONSTRAINT DF_STOKHAREKETLERI_STOKID DEFAULT (0),
  ISLEMTIPI tinyint NULL,
  ISLEMTARIHI datetime NULL,
  MIKTAR float NULL CONSTRAINT DF_STOKHAREKETLERI_MIKTAR DEFAULT (0),
  GIREN float NULL CONSTRAINT DF_STOKHAREKETLERI_GIREN DEFAULT (0),
  CIKAN float NULL CONSTRAINT DF_STOKHAREKETLERI_CIKAN DEFAULT (0),
  ACIKLAMA nvarchar(100) NULL,
  BIRIMADI nvarchar(15) NULL,
  CARIID int NULL CONSTRAINT DF_STOKHAREKETLERI_CARIID DEFAULT (0),
  EVRAKNO nvarchar(20) NULL,
  TUTAR float NULL CONSTRAINT DF_STOKHAREKETLERI_TOPLAMMALIYET DEFAULT (0),
  FATURAID int NULL CONSTRAINT DF_STOKHAREKETLERI_FATURAID DEFAULT (0),
  FATURA_H_ID int NULL CONSTRAINT DF_STOKHAREKETLERI_FATURASEPETIID DEFAULT (0),
  BIRIMFIYATI float NULL CONSTRAINT DF_STOKHAREKETLERI_BIRIMFIYATI DEFAULT (0),
  IND_ORANI float NULL CONSTRAINT DF_STOKHAREKETLERI_IND_ORANI DEFAULT (0),
  KDVORANI float NULL CONSTRAINT DF_STOKHAREKETLERI_KDVORANI DEFAULT (0),
  KDVTUTARI float NULL CONSTRAINT DF_STOKHAREKETLERI_KDVTUTARI DEFAULT (0),
  EK_GIREN float NULL CONSTRAINT DF_STOKHAREKETLERI_EK_GIREN DEFAULT (0),
  EK_CIKAN float NULL CONSTRAINT DF_STOKHAREKETLERI_EK_CIKAN DEFAULT (0),
  EK_ALIS_FIYATI float NULL CONSTRAINT DF_STOKHAREKETLERI_EK_ALIS_FIYATI DEFAULT (0),
  EK_SATIS_FIYATI float NULL CONSTRAINT DF_STOKHAREKETLERI_EK_SATIS_FIYATI DEFAULT (0),
  IND_EK_SATIS_FIYATI float NULL CONSTRAINT DF_STOKHAREKETLERI_IND_EK_SATIS_FIYATI DEFAULT (0),
  AKTIF bit NULL CONSTRAINT DF_dbo_STOK_H_AKTIF DEFAULT (1),
  DELETED bit NULL CONSTRAINT DF_dbo_STOK_H_DELETED DEFAULT (0),
  CREATEDAT datetime2(0) NULL CONSTRAINT DF_dbo_STOK_H_CREATEDAT DEFAULT (sysdatetime()),
  UPDATEDAT datetime2(0) NULL,
  DELETEDAT datetime2(0) NULL,
  USERID int NULL,
  USERIDUP int NULL
)
ON [PRIMARY]
GO

--
-- Create foreign key [FK_STOK_H_STOKID] on table [dbo].[STOK_H]
--
PRINT (N'Create foreign key [FK_STOK_H_STOKID] on table [dbo].[STOK_H]')
GO
ALTER TABLE dbo.STOK_H
  ADD CONSTRAINT FK_STOK_H_STOKID FOREIGN KEY (STOKID) REFERENCES dbo.STOK (ID)
GO

--
-- Create table [dbo].[SATIS_H]
--
PRINT (N'Create table [dbo].[SATIS_H]')
GO
CREATE TABLE dbo.SATIS_H (
  ID int IDENTITY,
  SATISID int NULL CONSTRAINT DF_SATISSEPETI_SATISLISTESIID DEFAULT (0),
  ISLEMTARIHI datetime NULL,
  STOKID int NULL CONSTRAINT DF_SATISSEPETI_STOKID DEFAULT (0),
  BIRIMFIYATI float NULL CONSTRAINT DF_SATISSEPETI_FIYAT DEFAULT (0),
  BIRIM nvarchar(15) NULL,
  MIKTAR float NULL CONSTRAINT DF_SATISSEPETI_ADET DEFAULT (0),
  TUTAR float NULL CONSTRAINT DF_SATISSEPETI_TUTAR DEFAULT (0),
  ACIKLAMA nvarchar(100) NULL,
  KDVTUTARI float NULL CONSTRAINT DF_SATISSEPETI_KDVTUTARI DEFAULT (0),
  KDVORANI float NULL CONSTRAINT DF_SATISSEPETI_KDVORANI DEFAULT (0),
  IND_ORANI float NULL CONSTRAINT DF_SATISSEPETI_IND_ORANI DEFAULT (0),
  AKTIF bit NULL CONSTRAINT DF_dbo_SATIS_H_AKTIF DEFAULT (1),
  DELETED bit NULL CONSTRAINT DF_dbo_SATIS_H_DELETED DEFAULT (0),
  CREATEDAT datetime2(0) NULL CONSTRAINT DF_dbo_SATIS_H_CREATEDAT DEFAULT (sysdatetime()),
  UPDATEDAT datetime2(0) NULL,
  DELETEDAT datetime2(0) NULL,
  USERID int NULL,
  USERIDUP int NULL,
  CONSTRAINT PK_SATISSEPETI PRIMARY KEY CLUSTERED (ID)
)
ON [PRIMARY]
GO

--
-- Create index [IX_SATIS_H_SATISLISTID] on table [dbo].[SATIS_H]
--
PRINT (N'Create index [IX_SATIS_H_SATISLISTID] on table [dbo].[SATIS_H]')
GO
CREATE INDEX IX_SATIS_H_SATISLISTID
  ON dbo.SATIS_H (SATISID)
  ON [PRIMARY]
GO

--
-- Create table [dbo].[SATIS]
--
PRINT (N'Create table [dbo].[SATIS]')
GO
CREATE TABLE dbo.SATIS (
  ID int IDENTITY,
  ISLEMTARIHI datetime NULL,
  ISLEMTIPI int NULL,
  TUTAR float NULL CONSTRAINT DF_SATISLISTESI_TUTAR DEFAULT (0),
  CARIID int NULL CONSTRAINT DF_SATISLISTESI_CARIID DEFAULT (0),
  ACIKLAMA nvarchar(100) NULL,
  POSID int NULL,
  ALISMALIYETI float NULL CONSTRAINT DF_SATISLISTESI_ALISMALIYETI DEFAULT (0),
  SATISTUTARI float NULL CONSTRAINT DF_SATISLISTESI_SATISTUTARI DEFAULT (0),
  KAR float NULL CONSTRAINT DF_SATISLISTESI_KAR DEFAULT (0),
  KDVTUTARI float NULL CONSTRAINT DF_SATISLISTESI_KDVTUTARI DEFAULT (0),
  IND_ORANI float NULL CONSTRAINT DF_SATISLISTESI_IND_ORANI DEFAULT (0),
  IND_TOPLAMI float NULL CONSTRAINT DF_SATISLISTESI_IND_TOPLAMI DEFAULT (0),
  KDVMATRAHI float NULL CONSTRAINT DF_SATISLISTESI_KDV_MATRAHI DEFAULT (0),
  FATURAID int NULL CONSTRAINT DF_SATISLISTESI_FATURAID DEFAULT (0),
  ACIKLAMA2 nvarchar(100) NULL,
  AKTIF bit NULL CONSTRAINT DF_dbo_SATIS_AKTIF DEFAULT (1),
  DELETED bit NULL CONSTRAINT DF_dbo_SATIS_DELETED DEFAULT (0),
  CREATEDAT datetime2(0) NULL CONSTRAINT DF_dbo_SATIS_CREATEDAT DEFAULT (sysdatetime()),
  UPDATEDAT datetime2(0) NULL,
  DELETEDAT datetime2(0) NULL,
  USERID int NULL,
  USERIDUP int NULL
)
ON [PRIMARY]
GO

--
-- Create index [KEY_SATIS_ID] on table [dbo].[SATIS]
--
PRINT (N'Create index [KEY_SATIS_ID] on table [dbo].[SATIS]')
GO
CREATE UNIQUE INDEX KEY_SATIS_ID
  ON dbo.SATIS (ID)
  ON [PRIMARY]
GO

--
-- Create table [dbo].[POS_H]
--
PRINT (N'Create table [dbo].[POS_H]')
GO
CREATE TABLE dbo.POS_H (
  ID int IDENTITY,
  POSID int NULL CONSTRAINT DF_POSKASA_POSID DEFAULT (0),
  TARIH datetime NULL,
  ACIKLAMA1 nvarchar(100) NULL,
  ACIKLAMA2 nvarchar(100) NULL,
  BORC float NULL CONSTRAINT DF_POSKASA_BORC DEFAULT (0),
  ALACAK float NULL CONSTRAINT DF_POSKASA_ALACAK DEFAULT (0),
  CARIID int NULL CONSTRAINT DF_POSKASA_CARIID DEFAULT (0),
  EVRAKNO nvarchar(20) NULL,
  FATURAID int NULL CONSTRAINT DF_POS__H_FATURAID DEFAULT (0),
  SATISID int NULL CONSTRAINT DF_POS__H_SATISLISTID DEFAULT (0),
  DELETED bit NULL CONSTRAINT DF_dbo_POS__H_DELETED DEFAULT (0),
  CREATEDAT datetime2(0) NULL CONSTRAINT DF_dbo_POS__H_CREATEDAT DEFAULT (sysdatetime()),
  UPDATEDAT datetime2(0) NULL,
  DELETEDAT datetime2(0) NULL,
  USERID int NULL,
  USERIDUP int NULL,
  CONSTRAINT PK_POSKASA PRIMARY KEY CLUSTERED (ID)
)
ON [PRIMARY]
GO

--
-- Create table [dbo].[POS]
--
PRINT (N'Create table [dbo].[POS]')
GO
CREATE TABLE dbo.POS (
  ID int IDENTITY,
  POSADI nvarchar(30) NOT NULL,
  HESAPKODU nvarchar(20) NULL,
  TERMINALNO nvarchar(20) NULL,
  BANKAADI nvarchar(30) NULL,
  UYEISYERINO nvarchar(20) NULL,
  AKTIF bit NULL CONSTRAINT DF_dbo_POS_AKTIF DEFAULT (1),
  DELETED bit NULL CONSTRAINT DF_dbo_POS_DELETED DEFAULT (0),
  CREATEDAT datetime2(0) NULL CONSTRAINT DF_dbo_POS_CREATEDAT DEFAULT (sysdatetime()),
  UPDATEDAT datetime2(0) NULL,
  DELETEDAT datetime2(0) NULL,
  USERID int NULL,
  USERIDUP int NULL,
  CONSTRAINT PK_POSLAR PRIMARY KEY CLUSTERED (ID)
)
ON [PRIMARY]
GO

--
-- Create table [dbo].[KASA_H]
--
PRINT (N'Create table [dbo].[KASA_H]')
GO
CREATE TABLE dbo.KASA_H (
  ID int IDENTITY,
  TARIH datetime NULL,
  ACIKLAMA1 nvarchar(100) NULL,
  ACIKLAMA2 nvarchar(100) NULL,
  GIREN float NULL CONSTRAINT DF_KASA_BORC DEFAULT (0),
  CIKAN float NULL CONSTRAINT DF_KASA_ALACAK DEFAULT (0),
  CARIID int NULL CONSTRAINT DF_KASA_CARIID DEFAULT (0),
  EVRAKNO nvarchar(20) NULL,
  FATURAID int NULL CONSTRAINT DF_KASA_FATURAID DEFAULT (0),
  SATISID int NULL CONSTRAINT DF_KASA_SATISLISTID DEFAULT (0),
  DELETED bit NULL CONSTRAINT DF_dbo_KASA_H_DELETED DEFAULT (0),
  CREATEDAT datetime2(0) NULL CONSTRAINT DF_dbo_KASA_H_CREATEDAT DEFAULT (sysdatetime()),
  UPDATEDAT datetime2(0) NULL,
  DELETEDAT datetime2(0) NULL,
  USERID int NULL,
  USERIDUP int NULL,
  CONSTRAINT PK_KASA PRIMARY KEY CLUSTERED (ID)
)
ON [PRIMARY]
GO

--
-- Create table [dbo].[CARI_H]
--
PRINT (N'Create table [dbo].[CARI_H]')
GO
CREATE TABLE dbo.CARI_H (
  ID int IDENTITY,
  CARIID int NOT NULL CONSTRAINT DF_CARIHAREKET_CARIID DEFAULT (0),
  ISLEMTARIHI datetime NULL,
  BORC float NULL CONSTRAINT DF_CARIHAREKET_BORC DEFAULT (0),
  ALACAK float NULL CONSTRAINT DF_CARIHAREKET_ALACAK DEFAULT (0),
  VADETARIHI datetime NULL,
  EVRAKNO nvarchar(20) NULL,
  POSID int NULL CONSTRAINT DF_CARIHAREKET_KASAID DEFAULT (0),
  ACIKLAMA1 nvarchar(100) NULL,
  ACIKLAMA2 nvarchar(100) NULL,
  ACIKLAMA3 nvarchar(100) NULL,
  ISLEMTIPI int NULL,
  FATURAID int NULL CONSTRAINT DF_CARIHAREKET_FATURAID DEFAULT (0),
  CEKSENETHID int NULL CONSTRAINT DF_CARIHAREKET_CEKSENET_H_ID DEFAULT (0),
  AKTIF bit NULL CONSTRAINT DF_dbo_CARI_H_AKTIF DEFAULT (1),
  DELETED bit NULL CONSTRAINT DF_dbo_CARI_H_DELETED DEFAULT (0),
  CREATEDAT datetime2(0) NULL CONSTRAINT DF_dbo_CARI_H_CREATEDAT DEFAULT (sysdatetime()),
  UPDATEDAT datetime2(0) NULL,
  DELETEDAT datetime2(0) NULL,
  USERID int NULL,
  USERIDUP int NULL,
  CONSTRAINT PK_CARIHAREKET PRIMARY KEY CLUSTERED (ID)
)
ON [PRIMARY]
GO

--
-- Create index [IX_CARIHAREKET_CARIID] on table [dbo].[CARI_H]
--
PRINT (N'Create index [IX_CARIHAREKET_CARIID] on table [dbo].[CARI_H]')
GO
CREATE INDEX IX_CARIHAREKET_CARIID
  ON dbo.CARI_H (CARIID)
  ON [PRIMARY]
GO

--
-- Create index [IX_CARIHAREKET_CEKSENET_H_ID] on table [dbo].[CARI_H]
--
PRINT (N'Create index [IX_CARIHAREKET_CEKSENET_H_ID] on table [dbo].[CARI_H]')
GO
CREATE INDEX IX_CARIHAREKET_CEKSENET_H_ID
  ON dbo.CARI_H (CEKSENETHID)
  ON [PRIMARY]
GO

--
-- Create index [IX_CARIHAREKET_FATURAID] on table [dbo].[CARI_H]
--
PRINT (N'Create index [IX_CARIHAREKET_FATURAID] on table [dbo].[CARI_H]')
GO
CREATE INDEX IX_CARIHAREKET_FATURAID
  ON dbo.CARI_H (FATURAID)
  ON [PRIMARY]
GO

--
-- Create index [IX_CARIHAREKET_ISLEMTURU] on table [dbo].[CARI_H]
--
PRINT (N'Create index [IX_CARIHAREKET_ISLEMTURU] on table [dbo].[CARI_H]')
GO
CREATE INDEX IX_CARIHAREKET_ISLEMTURU
  ON dbo.CARI_H (ISLEMTIPI)
  ON [PRIMARY]
GO

--
-- Create index [IX_CARIHAREKET_KASAID] on table [dbo].[CARI_H]
--
PRINT (N'Create index [IX_CARIHAREKET_KASAID] on table [dbo].[CARI_H]')
GO
CREATE INDEX IX_CARIHAREKET_KASAID
  ON dbo.CARI_H (POSID)
  ON [PRIMARY]
GO

--
-- Create table [dbo].[CARI]
--
PRINT (N'Create table [dbo].[CARI]')
GO
CREATE TABLE dbo.CARI (
  ID int IDENTITY,
  CARIKODU nvarchar(80) NOT NULL,
  UNVAN nvarchar(100) NOT NULL,
  TARIH datetime NULL,
  GROUPID int NULL,
  MESLEK nvarchar(20) NULL,
  ILCE nvarchar(20) NULL,
  SEHIR nvarchar(20) NULL,
  POSTAKODU nvarchar(10) NULL,
  ULKE nvarchar(20) NULL,
  VERGIDAIRESI nvarchar(20) NULL,
  VERGINO nvarchar(15) NULL,
  BANKA nvarchar(20) NULL,
  BANKAHESAPNO nvarchar(30) NULL,
  ISTELEFONU1 nvarchar(15) NULL,
  ISTELEFONU2 nvarchar(15) NULL,
  FAX nvarchar(15) NULL,
  CEPTELEFONU nvarchar(15) NULL,
  EVTELEFONU nvarchar(15) NULL,
  EMAIL nvarchar(50) NULL,
  ADRES1 nvarchar(50) NULL,
  ADRES2 nvarchar(50) NULL,
  ADRES3 nvarchar(50) NULL,
  ACIKLAMA1 nvarchar(100) NULL,
  ACIKLAMA2 nvarchar(100) NULL,
  ACIKLAMA3 nvarchar(100) NULL,
  RESIM nvarchar(150) NULL,
  YETKILI nvarchar(30) NULL,
  BORC float NULL CONSTRAINT DF_CARI_BORC DEFAULT (0),
  ALACAK float NULL CONSTRAINT DF_CARI_ALACAK DEFAULT (0),
  BAKIYE float NULL CONSTRAINT DF_CARI_BAKYE DEFAULT (0),
  VERESIYE_LIMITI float NULL CONSTRAINT DF_CARI_VERESIYE_LIMITI DEFAULT (0),
  VERESIYE_UYAR bit NULL CONSTRAINT DF_CARI_VERESIYE_UYAR DEFAULT (0),
  VERESIYE_SURESI int NULL CONSTRAINT DF_CARI_VERESIYE_SURESI DEFAULT (0),
  RENK int NULL,
  EMAIL2 nvarchar(50) NULL,
  EMAIL3 nvarchar(50) NULL,
  EMAIL_SEC bit NULL CONSTRAINT DF_CARI_EMAIL_SEC DEFAULT (0),
  TIPI int NULL CONSTRAINT DF_CARI_CK_TYPE DEFAULT (0),
  CARI_NOTE ntext NULL,
  AKTIF bit NULL CONSTRAINT DF_dbo_CARI_AKTIF DEFAULT (1),
  DELETED bit NULL CONSTRAINT DF_dbo_CARI_DELETED DEFAULT (0),
  CREATEDAT datetime2(0) NULL CONSTRAINT DF_dbo_CARI_CREATEDAT DEFAULT (sysdatetime()),
  UPDATEDAT datetime2(0) NULL,
  DELETEDAT datetime2(0) NULL,
  USERID int NULL,
  USERIDUP int NULL,
  CONSTRAINT PK_CARI PRIMARY KEY CLUSTERED (ID),
  CONSTRAINT IX_CARI UNIQUE (CARIKODU)
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO