USE KHPRO
GO

IF DB_NAME() <> N'KHPRO' SET NOEXEC ON
GO

--
-- Create table [dbo].[____FATURA_H]
--
PRINT (N'Create table [dbo].[____FATURA_H]')
GO
CREATE TABLE dbo.____FATURA_H (
  ID int IDENTITY,
  TARIH datetime NULL,
  FATURAID int NULL,
  STOKID int NULL,
  BIRIMFIYATI float NULL,
  MIKTAR float NULL,
  BIRIM nvarchar(15) NULL,
  TUTAR float NULL,
  ACIKLAMA nvarchar(100) NULL,
  COMNAMETIME nvarchar(80) NULL,
  KDVORANI int NULL,
  KDVTUTARI float NULL,
  IND_ORANI float NULL,
  IND_ORANI2 float NULL,
  IND_TUTARI float NULL,
  AKTIF bit NOT NULL,
  DELETED bit NOT NULL,
  CREATEDAT datetime2(0) NOT NULL,
  UPDATEDAT datetime2(0) NULL,
  DELETEDAT datetime2(0) NULL,
  USERID int NULL,
  USERIDUP int NULL
)
ON [PRIMARY]
GO

--
-- Create table [dbo].[____FATURA]
--
PRINT (N'Create table [dbo].[____FATURA]')
GO
CREATE TABLE dbo.____FATURA (
  ID int IDENTITY,
  TARIH datetime NULL,
  ISLEMTURU nvarchar(20) NULL,
  TUTAR float NULL,
  EVRAKNO nvarchar(80) NULL,
  CARIID int NULL,
  ACIKLAMA nvarchar(100) NULL,
  PERSONEL nvarchar(20) NULL,
  COMNAMETIME nvarchar(80) NULL,
  UPDATECOUNT int NULL,
  IND_ORANI float NULL,
  IND_ORANI2 float NULL,
  IND_TOPLAMI float NULL,
  IND_TUTARI float NULL,
  KDVMATRAHI float NULL,
  KDVTUTARI float NULL,
  FATURATIPI nvarchar(20) NULL,
  SAAT datetime NULL,
  SEVKTARIHI datetime NULL,
  IRSALIYENO nvarchar(20) NULL,
  PRINTED bit NULL,
  SATISID int NULL,
  VADE_TARIHI datetime NULL,
  AKTIF bit NOT NULL,
  DELETED bit NOT NULL,
  CREATEDAT datetime2(0) NOT NULL,
  UPDATEDAT datetime2(0) NULL,
  DELETEDAT datetime2(0) NULL,
  USERID int NULL,
  USERIDUP int NULL,
  CONSTRAINT PK_FATURA PRIMARY KEY CLUSTERED (ID)
)
ON [PRIMARY]
GO

--
-- Create table [dbo].[____CEKSENET_H]
--
PRINT (N'Create table [dbo].[____CEKSENET_H]')
GO
CREATE TABLE dbo.____CEKSENET_H (
  ID int NOT NULL,
  CEKSENETID int NULL CONSTRAINT DF_CEKSENET_H_CEKSENET_ID DEFAULT (0),
  TYPE_CEKSENET_H int NULL CONSTRAINT DF_CEKSENET_H_TYPE_CEKSENET_H DEFAULT (0),
  ISLEMTARIHI datetime NULL CONSTRAINT DF_CEKSENET_H_ISLEMTARIHI DEFAULT (getdate()),
  CARIID int NULL CONSTRAINT DF_CEKSENET_H_CARIID DEFAULT (0),
  PERSONEL nvarchar(20) NULL,
  TUTAR float NULL CONSTRAINT DF_CEKSENET_H_TUTAR DEFAULT (0),
  BANKA nvarchar(50) NULL,
  ACIKLAMA1 nvarchar(100) NULL,
  ACIKLAMA2 nvarchar(100) NULL,
  UPDATECOUNT int NULL CONSTRAINT DF_CEKSENET_H_UPDATECOUNT DEFAULT (0),
  AKTIF bit NOT NULL CONSTRAINT DF_dbo_____CEKSENET_H_AKTIF DEFAULT (1),
  DELETED bit NOT NULL CONSTRAINT DF_dbo_____CEKSENET_H_DELETED DEFAULT (0),
  CREATEDAT datetime2(0) NOT NULL CONSTRAINT DF_dbo_____CEKSENET_H_CREATEDAT DEFAULT (sysdatetime()),
  UPDATEDAT datetime2(0) NULL,
  DELETEDAT datetime2(0) NULL,
  USERID int NULL,
  USERIDUP int NULL,
  CONSTRAINT PK_CEKSENET_H PRIMARY KEY CLUSTERED (ID)
)
ON [PRIMARY]
GO

--
-- Create table [dbo].[____CEKSENET]
--
PRINT (N'Create table [dbo].[____CEKSENET]')
GO
CREATE TABLE dbo.____CEKSENET (
  ID int NOT NULL,
  CEKORSENET bit NULL CONSTRAINT DF_CEKSENET_CEKORSENET DEFAULT (0),
  KENDIORMUSTERI bit NULL CONSTRAINT DF_CEKSENET_KENDIORMUSTERI DEFAULT (0),
  TAKIPNO nvarchar(15) NULL,
  SERINO nvarchar(20) NULL,
  TARIH datetime NULL CONSTRAINT DF_CEKSENET_TARIH DEFAULT (getdate()),
  VADE datetime NULL,
  BANKA nvarchar(50) NULL,
  SUBE nvarchar(50) NULL,
  HESAPNO nvarchar(50) NULL,
  TUTAR float NULL CONSTRAINT DF_CEKSENET_TUTAR DEFAULT (0),
  MUHABIRSUBE nvarchar(50) NULL,
  ODEMEYERI nvarchar(50) NULL,
  MUSTERICIROLADI bit NULL CONSTRAINT DF_CEKSENET_MUSTERICIROLADI DEFAULT (0),
  KESIDECI nvarchar(50) NULL,
  GRUP nvarchar(20) NULL,
  ACIKLAMA1 nvarchar(100) NULL,
  ACIKLAMA2 nvarchar(100) NULL,
  KEFIL_ID int NULL CONSTRAINT DF_CEKSENET_KEFIL_ID DEFAULT (0),
  UPDATECOUNT int NULL CONSTRAINT DF_CEKSENET_UPDATECOUNT DEFAULT (0),
  PERSONEL nvarchar(20) NULL,
  AKTIF bit NOT NULL CONSTRAINT DF_dbo_____CEKSENET_AKTIF DEFAULT (1),
  DELETED bit NOT NULL CONSTRAINT DF_dbo_____CEKSENET_DELETED DEFAULT (0),
  CREATEDAT datetime2(0) NOT NULL CONSTRAINT DF_dbo_____CEKSENET_CREATEDAT DEFAULT (sysdatetime()),
  UPDATEDAT datetime2(0) NULL,
  DELETEDAT datetime2(0) NULL,
  USERID int NULL,
  USERIDUP int NULL,
  CONSTRAINT PK_CEKSENET PRIMARY KEY CLUSTERED (ID)
)
ON [PRIMARY]
GO